%% SCRIPT 19: In-Silico Langevin Validation (HNN Model)
% This script applies the Langevin Inverse Modeling framework to the 
% biophysical HNN simulation data.
%
% GOAL: Validation.
% Does the "JME Model" (Poor Arborization, GABA deficit, Microdysgenesis)
% produce a Stiffer (more rigid) potential landscape than the Control model?
%
% INPUTS: 
% - InSilico_Control.mat
% - InSilico_JME.mat
% (Generated by Python HNN script)

clc; %close all;

%% --- 1. Setup Parameters ---
dt_sim = 1/100; % Simulation was downsampled to 100 Hz (10ms)
num_bins = 15;  % Reduced from 20 to accommodate shorter simulation length
x_axis_common = linspace(-3, 3, num_bins); 

files = {'InSilico_Control.mat', 'InSilico_JME.mat'};
labels = {'Control Model', 'JME Model'};
colors = {'b', 'r'};

results = []; % [Stiffness(b), Temperature(D)]
potentials = []; % Store curves

%% --- 2. Main Simulation Loop ---
disp('Analyzing In-Silico Dynamics...');

for i = 1:length(files)
    filename = files{i};
    if ~isfile(filename)
        warning('File %s not found. Run Python script first.', filename);
        continue;
    end
    
    fprintf('Processing %s...\n', labels{i});
    data = load(filename);
    
    % Extract Data
    % A_dyn: [N x N] (Static correlation for this simulation run)
    % elects: [N x Time]
    A = double(data.A_dyn);
    X = double(data.elects);
    
    [N, n_samples] = size(X);
    
    % --- Calculate Global Smoothness Time Series ---
    % S(t) = x(t)' L x(t)
    
    % 1. Laplacian
    % Check for NaNs or disconnected nodes
    A(isnan(A)) = 0;
    D = diag(sum(A, 2));
    % Normalized Laplacian
    d_inv_sqrt = 1./sqrt(diag(D) + eps);
    L = eye(N) - diag(d_inv_sqrt) * A * diag(d_inv_sqrt);
    
    % 2. Signal Power (Alpha Power)
    % HNN output is voltage. We square it to match EEG "Power" analysis.
    P = X.^2;
    
    % 3. Calculate Smoothness
    % Vectorized: diag(P' * L * P) -> sum(P .* (L*P))
    LP = L * P;
    smooth_ts = sum(P .* LP, 1);
    
    % --- Kramers-Moyal Reconstruction ---
    
    % 1. Z-Score (Normalize State Space)
    x_state = (smooth_ts - mean(smooth_ts)) / std(smooth_ts);
    dx = diff(x_state);
    
    % 2. Adaptive Binning with Fallback
    limits = prctile(x_state, [2.5, 97.5]);
    
    % Safety: If distribution is too narrow/flat, use standard Z range
    if abs(limits(2)-limits(1)) < 0.1
        limits = [-3, 3]; 
    end
    
    edges = linspace(limits(1), limits(2), num_bins+1);
    centers = (edges(1:end-1) + edges(2:end)) / 2;
    
    [~, bin_idx] = histc(x_state(1:end-1), edges);
    
    Drift = nan(1, num_bins);
    Diffusion = nan(1, num_bins);
    
    for b = 1:num_bins
        mask = (bin_idx == b);
        % Relaxed threshold for short simulations (5 samples instead of 10)
        if sum(mask) > 5
            Drift(b) = mean(dx(mask)) / dt_sim;
            Diffusion(b) = var(dx(mask)) / dt_sim;
        end
    end
    
    % 3. Fit Potential
    valid = ~isnan(Drift);
    if sum(valid) < 4
        warning('Not enough valid bins for %s (Found %d)', labels{i}, sum(valid));
        results = [results; NaN, NaN];
        potentials = [potentials; nan(1, num_bins)];
        continue;
    end
    
    % Polynomial Fit (F(x) = -ax^3 - bx - c)
    [p, ~] = polyfit(centers(valid), Drift(valid), 3);
    
    % Extract Metrics
    b_stiffness = -p(3)/2; % Quadratic Curvature
    d_temp = mean(Diffusion(valid));
    
    results = [results; b_stiffness, d_temp];
    
    % Reconstruct Curve for Plotting
    U_curve = -cumsum(Drift(valid)) * (centers(2)-centers(1));
    U_curve = U_curve - min(U_curve); % Anchor to 0
    
    % Interpolate to common axis
    U_interp = interp1(centers(valid), U_curve, x_axis_common, 'linear', NaN);
    potentials = [potentials; U_interp];
    
end

disp('Analysis Complete.');

%% --- 3. Visualization ---
if isempty(results), return; end

fig = figure('Name', 'In-Silico Langevin Validation', 'Color', 'w');
t = tiledlayout(1, 3, 'TileSpacing', 'compact', 'Padding', 'compact');

% 1. Potential Landscape Comparison
nexttile;
hold on;
plot(x_axis_common, potentials(1,:), 'Color', colors{1}, 'LineWidth', 2.5);
plot(x_axis_common, potentials(2,:), 'Color', colors{2}, 'LineWidth', 2.5);
xlabel('Network State (Z-Smoothness)'); ylabel('Potential Energy U(x)');
title('Simulated Energy Landscapes');
legend(labels, 'Location', 'north'); 
grid on;

% 2. Stiffness Bar Chart
nexttile;
b = bar([1, 2], results(:,1));
b.FaceColor = 'flat';
b.CData(1,:) = [0 0 1]; % Blue
b.CData(2,:) = [1 0 0]; % Red
xticks([1 2]); xticklabels(labels);
ylabel('Stiffness (Curvature b)');
title('Landscape Rigidity');
grid on;

% 3. Temperature Bar Chart
nexttile;
b2 = bar([1, 2], results(:,2));
b2.FaceColor = 'flat';
b2.CData(1,:) = [0 0 1]; 
b2.CData(2,:) = [1 0 0];
xticks([1 2]); xticklabels(labels);
ylabel('Temperature (Diffusion D)');
title('Intrinsic Noise');
grid on;

% Print Results
fprintf('\n--- SIMULATION RESULTS ---\n');
fprintf('Control Model: Stiffness = %.3f, Temp = %.3f\n', results(1,1), results(1,2));
fprintf('JME Model:     Stiffness = %.3f, Temp = %.3f\n', results(2,1), results(2,2));
fprintf('--------------------------\n');
if results(2,1) > results(1,1)
    fprintf('VALIDATION SUCCESS: JME Model is STIFFER (More Rigid).\n');
else
    fprintf('VALIDATION RESULT: JME Model is LESS stiff.\n');
end